# fRom our excel

CATEGORY_TO_SUBCATEGORY = [
    ("", "Canonical"),
    ("Mathematical & Scientific Notation", "Spelled out"),
    ("Noise", "Keyboard proximity errors"),
    ("Social Media & Informal Text", "Colloquial"),
    ("Script / Orthography", "Code/language/script switching"),
    ("Script / Orthography", "Equivalent expressions"),
    ("Script / Orthography", "Similar words"),
    ("Grammatical errors", "Grammatical errors"),
    ("Noise", "Space removal"),
    ("Script / Orthography", "Web search query"),
    ("Script / Orthography", "Abbreviations"),
    ("Temporal Expressions", "Date formats"),
    ("Script / Orthography", "Dialects"),
    ("Script / Orthography", "Orthographic errors"),
    ("Morphological Challenges", "Contractions"),
    ("Social Media & Informal Text", "Word reordering"),
    ("Structural Text Elements", "Scripted text"),
    ("Noise", "Character deletion"),
    ("Mathematical & Scientific Notation", "Superscript/subscript"),
    ("Morphological Challenges", "Inflections"),
    ("Script / Orthography", "Romanization"),
    ("Script / Orthography", "Word Spacing/Zero-width characters/Extra Space"),
    ("Script / Orthography", "English keyboard"),
    ("Noise", "Typographical errors"),
    ("Mathematical & Scientific Notation", "LaTeX"),
    ("Script / Orthography", "Substitution"),
    ("Context-Dependent Ambiguities", "Wiki-jargon"),
    ("Script / Orthography", "Historical spelling"),
    ("Social Media & Informal Text", "Emoji substitution"),
    ("Morphological Challenges", "Compounds"),
    ("Noise", "OCR Errors"),
    ("Social Media & Informal Text", "Letter repetition for emphasis"),
    ("Script / Orthography", "Homoglyphs"),
    ("Structural Text Elements", "Hyphenated spelling"),
    ("Structural Text Elements", "Macron Diacritic"),
    ("Structural Text Elements", "Capitalization"),
    ("Structural Text Elements", "Spaced styling"),
    ("Structural Text Elements", "Superscript/subscript styling"),
    ("Structural Text Elements", "Lowercase"),
    ("Social Media & Informal Text", "Character substitution"),
    ("Script / Orthography", "Currency symbol"),
    ("Mathematical & Scientific Notation", "Decorative Unicode"),
    ("Mathematical & Scientific Notation", "Farsi"),
    ("Mathematical & Scientific Notation", "Turkish"),
    ("Mathematical & Scientific Notation", "Italian"),
    ("Mathematical & Scientific Notation", "Chinese"),
    ("Morphological Challenges", "Derivations"),
    ("Noise", "Arabic Keyboard for Farsi"),
    ("Script / Orthography", "Partially romanized"),
    ("Script / Orthography", "Traditional"),
    ("Script / Orthography", "Number Romanization"),
    ("Script / Orthography", "Optional diacritics"),
    ("Script / Orthography", "Plausible diacritics errors"),
    ("Social Media & Informal Text", "Phonetic spelling"),
    ("Structural Text Elements", "Fullwidth Characters"),
    ("Structural Text Elements", "Upside Down/Rotated"),
    ("Structural Text Elements", "Unusual formatting"),
    ("Structural Text Elements", "Double struck"),
    ("Structural Text Elements", "Unicode formatting"),
    ("Morphological Challenges", "Morpheme separation"),
    ("Structural Text Elements", "Enclosed Characters"),
    ("Structural Text Elements", "Strikethrough"),
    ("Structural Text Elements", "Diacriticized styling"),
    ("Mathematical & Scientific Notation", "Numerical formats"),
    ("Code & Technical Content", "Buggy code"),
    ("Code & Technical Content", "Comments across languages"),
    ("Code & Technical Content", "String literals"),
    ("Code & Technical Content", "Syntax and punctuation variations"),
    ("Code & Technical Content", "Variable naming conventions"),
    ("Code & Technical Content", "Whitespace variations"),
    ("Context-Dependent Ambiguities", "Domain-specific punctuation"),
    ("Context-Dependent Ambiguities", "Quotes & parentheses"),
    ("Context-Dependent Ambiguities", "Rare n-grams"),
    ("Context-Dependent Ambiguities", "Sentence boundaries"),
    ("Context-Dependent Ambiguities", "Cultural references"),
    ("Grammatical errors", "Wrong preposition"),
    ("Grammatical errors", "Wrong article"),
    ("Grammatical errors", "Wrong gender/number"),
    ("Language Contact", "Calques"),
    ("Language Contact", "Transliteration"),
    ("Mathematical & Scientific Notation", "Chemical formulas"),
    ("Mathematical & Scientific Notation", "Equations with mixed notation"),
    ("Mathematical & Scientific Notation", "Scientific notation"),
    ("Morphological Challenges", "Affixation edge cases"),
    ("Morphological Challenges", "Clitics"),
    ("Named Entities", "Academic citations"),
    ("Named Entities", "Place names with apostrophes"),
    ("Named Entities", "Special names across cultures"),
    ("Named Entities", "Technical product names"),
    ("Noise", "Noise injection"),
    ("Noise", "Chinese-character-selection-proximity error"),
    ("Noise", "Permutations"),
    ("Noise", "Unintentional character substitution"),
    ("Script / Orthography", "Regional spelling variations"),
    ("Script / Orthography", "Proper nouns with unusual capitalization"),
    ("Script / Orthography", "Abbreviations (with periods)"),
    ("Script / Orthography", "Brand names with punctuation"),
    ("Social Media & Informal Text", "Deliberate misspellings"),
    ("Structural Text Elements", "Email addresses"),
    ("Structural Text Elements", "Headers and section titles"),
    ("Structural Text Elements", "List markers"),
    ("Structural Text Elements", "Text decorations"),
    ("Structural Text Elements", "URLs and file paths"),
    ("Temporal Expressions", "Locality-dependent formats"),
    ("Temporal Expressions", "Time zones"),
    ("Temporal Expressions", "Relative time expressions"),
    ("Mathematical & Scientific Notation", "ASCII"),
    ("Mathematical & Scientific Notation", "Additional spaces"),
    ("Noise", "Character injection"),
    ("Script / Orthography", "Random diacritics addition"),
    ("Language Contact", "Borrowing"),
    ("Mathematical & Scientific Notation", "Unit combinations"),
    ("Script / Orthography", "Wrong h"),
    ("Script / Orthography", "Double consonant"),
    ("Script / Orthography", "Wrong letter"),
    ("Script / Orthography", "Diacritics Removal"),
]

SUBCATEGORY_TO_CATEGORY = {v: k for k, v in CATEGORY_TO_SUBCATEGORY}
# print(SUBCATEGORY_TO_CATEGORY)
SUBCATEGORY_TO_CATEGORY = {
    "Canonical": "",
    "Spelled out": "Mathematical & Scientific Notation",
    "Keyboard proximity errors": "Noise",
    "Colloquial": "Social Media & Informal Text",
    "Code/language/script switching": "Script / Orthography",
    "Equivalent expressions": "Script / Orthography",
    "Similar words": "Script / Orthography",
    "Grammatical errors": "Grammatical errors",
    "Space removal": "Noise",
    "Web search query": "Script / Orthography",
    "Abbreviations": "Script / Orthography",
    "Date formats": "Temporal Expressions",
    "Dialects": "Script / Orthography",
    "Orthographic errors": "Script / Orthography",
    "Contractions": "Morphological Challenges",
    "Word reordering": "Social Media & Informal Text",
    "Scripted text": "Structural Text Elements",
    "Character deletion": "Noise",
    "Superscript/subscript": "Mathematical & Scientific Notation",
    "Inflections": "Morphological Challenges",
    "Romanization": "Script / Orthography",
    "Word Spacing/Zero-width characters/Extra Space": "Script / Orthography",
    "English keyboard": "Script / Orthography",
    "Typographical errors": "Noise",
    "LaTeX": "Mathematical & Scientific Notation",
    "Substitution": "Script / Orthography",
    "Wiki-jargon": "Context-Dependent Ambiguities",
    "Historical spelling": "Script / Orthography",
    "Emoji substitution": "Social Media & Informal Text",
    "Compounds": "Morphological Challenges",
    "OCR Errors": "Noise",
    "Letter repetition for emphasis": "Social Media & Informal Text",
    "Homoglyphs": "Script / Orthography",
    "Hyphenated spelling": "Structural Text Elements",
    "Macron Diacritic": "Structural Text Elements",
    "Capitalization": "Structural Text Elements",
    "Spaced styling": "Structural Text Elements",
    "Superscript/subscript styling": "Structural Text Elements",
    "Lowercase": "Structural Text Elements",
    "Character substitution": "Social Media & Informal Text",
    "Currency symbol": "Script / Orthography",
    "Decorative Unicode": "Mathematical & Scientific Notation",
    "Farsi": "Mathematical & Scientific Notation",
    "Turkish": "Mathematical & Scientific Notation",
    "Italian": "Mathematical & Scientific Notation",
    "Chinese": "Mathematical & Scientific Notation",
    "Derivations": "Morphological Challenges",
    "Arabic Keyboard for Farsi": "Noise",
    "Partially romanized": "Script / Orthography",
    "Traditional": "Script / Orthography",
    "Number Romanization": "Script / Orthography",
    "Optional diacritics": "Script / Orthography",
    "Plausible diacritics errors": "Script / Orthography",
    "Phonetic spelling": "Social Media & Informal Text",
    "Fullwidth Characters": "Structural Text Elements",
    "Upside Down/Rotated": "Structural Text Elements",
    "Unusual formatting": "Structural Text Elements",
    "Double struck": "Structural Text Elements",
    "Unicode formatting": "Structural Text Elements",
    "Morpheme separation": "Morphological Challenges",
    "Enclosed Characters": "Structural Text Elements",
    "Strikethrough": "Structural Text Elements",
    "Diacriticized styling": "Structural Text Elements",
    "Numerical formats": "Mathematical & Scientific Notation",
    "Buggy code": "Code & Technical Content",
    "Comments across languages": "Code & Technical Content",
    "String literals": "Code & Technical Content",
    "Syntax and punctuation variations": "Code & Technical Content",
    "Variable naming conventions": "Code & Technical Content",
    "Whitespace variations": "Code & Technical Content",
    "Domain-specific punctuation": "Context-Dependent Ambiguities",
    "Quotes & parentheses": "Context-Dependent Ambiguities",
    "Rare n-grams": "Context-Dependent Ambiguities",
    "Sentence boundaries": "Context-Dependent Ambiguities",
    "Cultural references": "Context-Dependent Ambiguities",
    "Wrong preposition": "Grammatical errors",
    "Wrong article": "Grammatical errors",
    "Wrong gender/number": "Grammatical errors",
    "Calques": "Language Contact",
    "Transliteration": "Language Contact",
    "Chemical formulas": "Mathematical & Scientific Notation",
    "Equations with mixed notation": "Mathematical & Scientific Notation",
    "Scientific notation": "Mathematical & Scientific Notation",
    "Affixation edge cases": "Morphological Challenges",
    "Clitics": "Morphological Challenges",
    "Academic citations": "Named Entities",
    "Place names with apostrophes": "Named Entities",
    "Special names across cultures": "Named Entities",
    "Technical product names": "Named Entities",
    "Noise injection": "Noise",
    "Chinese-character-selection-proximity error": "Noise",
    "Permutations": "Noise",
    "Unintentional character substitution": "Noise",
    "Regional spelling variations": "Script / Orthography",
    "Proper nouns with unusual capitalization": "Script / Orthography",
    "Abbreviations (with periods)": "Script / Orthography",
    "Brand names with punctuation": "Script / Orthography",
    "Deliberate misspellings": "Social Media & Informal Text",
    "Email addresses": "Structural Text Elements",
    "Headers and section titles": "Structural Text Elements",
    "List markers": "Structural Text Elements",
    "Text decorations": "Structural Text Elements",
    "URLs and file paths": "Structural Text Elements",
    "Locality-dependent formats": "Temporal Expressions",
    "Time zones": "Temporal Expressions",
    "Relative time expressions": "Temporal Expressions",
    "ASCII": "Mathematical & Scientific Notation",
    "Additional spaces": "Mathematical & Scientific Notation",
    "Character injection": "Noise",
    "Random diacritics addition": "Script / Orthography",
    "Borrowing": "Language Contact",
    "Unit combinations": "Mathematical & Scientific Notation",
    "Wrong h": "Script / Orthography",
    "Double consonant": "Script / Orthography",
    "Wrong letter": "Script / Orthography",
    "Diacritics Removal": "Script / Orthography",
}
