import re
import socket
from enum import Enum


class Hosts(str, Enum):
    vector = "vector"
    dcs = "dcs"
    local = "local"


def get_host():
    # Get hostname
    hostname = socket.gethostname()
    if "vremote" in hostname or re.match(r"gpu.*\.cluster\.local", hostname):
        return Hosts.vector
    # TODO: for dcs
    elif "guppy" in hostname:
        return Hosts.dcs
    return Hosts.local


VECTOR_HF_MAPPING = {
    "ai21/AI21-Jamba-1.5-Mini": "/model-weights/AI21-Jamba-1.5-Mini",
    "facebook/all-MiniLM-L6-v2": "/model-weights/all-MiniLM-L6-v2",
    "CohereForAI/aya-expanse-32b": "/model-weights/aya-expanse-32b",
    "BAAI/bge-base-en-v1.5": "/model-weights/bge-base-en-v1.5",
    "BAAI/bge-multilingual-gemma2": "/model-weights/bge-multilingual-gemma2",
    "c4ai/c4ai-command-r-08-2024": "/model-weights/c4ai-command-r-08-2024",
    "c4ai/c4ai-command-r-plus": "/model-weights/c4ai-command-r-plus",
    "c4ai/c4ai-command-r-plus-08-2024": "/model-weights/c4ai-command-r-plus-08-2024",
    "openai/clip-vit-base-patch16": "/model-weights/clip-vit-base-patch16",
    "openai/clip-vit-large-patch14-336": "/model-weights/clip-vit-large-patch14-336",
    "codellama/CodeLlama-13b": "/model-weights/CodeLlama-13b",
    "codellama/CodeLlama-13b-hf": "/model-weights/CodeLlama-13b-hf",
    "codellama/CodeLlama-13b-Instruct": "/model-weights/CodeLlama-13b-Instruct",
    "codellama/CodeLlama-13b-Instruct-hf": "/model-weights/CodeLlama-13b-Instruct-hf",
    "codellama/CodeLlama-13b-Python-hf": "/model-weights/CodeLlama-13b-Python-hf",
    "codellama/CodeLlama-34b": "/model-weights/CodeLlama-34b",
    "codellama/CodeLlama-34b-hf": "/model-weights/CodeLlama-34b-hf",
    "codellama/CodeLlama-34b-Instruct": "/model-weights/CodeLlama-34b-Instruct",
    "codellama/CodeLlama-34b-Instruct-hf": "/model-weights/CodeLlama-34b-Instruct-hf",
    "codellama/CodeLlama-70b-hf": "/model-weights/CodeLlama-70b-hf",
    "codellama/CodeLlama-70b-Instruct-hf": "/model-weights/CodeLlama-70b-Instruct-hf",
    "codellama/CodeLlama-70b-Python-hf": "/model-weights/CodeLlama-70b-Python-hf",
    "codellama/CodeLlama-7b": "/model-weights/CodeLlama-7b",
    "codellama/CodeLlama-7b-hf": "/model-weights/CodeLlama-7b-hf",
    "codellama/CodeLlama-7b-Instruct": "/model-weights/CodeLlama-7b-Instruct",
    "codellama/CodeLlama-7b-Instruct-hf": "/model-weights/CodeLlama-7b-Instruct-hf",
    "codellama/CodeLlama-7b-Python-hf": "/model-weights/CodeLlama-7b-Python-hf",
    "facebook/data2vec": "/model-weights/data2vec",
    "databricks/dbrx-instruct": "/model-weights/dbrx-instruct",
    "deepseek-ai/deepseek-math-7b-instruct": "/model-weights/deepseek-math-7b-instruct",
    "deepseek-ai/DeepSeek-R1": "/model-weights/DeepSeek-R1",
    "deepseek-ai/DeepSeek-R1-Distill-Llama-70B": "/model-weights/DeepSeek-R1-Distill-Llama-70B",
    "deepseek-ai/DeepSeek-R1-Distill-Llama-8B": "/model-weights/DeepSeek-R1-Distill-Llama-8B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": "/model-weights/DeepSeek-R1-Distill-Qwen-14B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": "/model-weights/DeepSeek-R1-Distill-Qwen-1.5B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B": "/model-weights/DeepSeek-R1-Distill-Qwen-32B",
    "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B": "/model-weights/DeepSeek-R1-Distill-Qwen-7B",
    "deepseek-ai/deepseek-vl2": "/model-weights/deepseek-vl2",
    "deepseek-ai/deepseek-vl2-small": "/model-weights/deepseek-vl2-small",
    "intfloat/e5-mistral-7b-instruct": "/model-weights/e5-mistral-7b-instruct",
    "google/gemma-2-27b": "/model-weights/gemma-2-27b",
    "google/gemma-2-27b-it": "/model-weights/gemma-2-27b-it",
    "google/gemma-2-9b": "/model-weights/gemma-2-9b",
    "google/gemma-2-9b-it": "/model-weights/gemma-2-9b-it",
    "google/gemma-2b": "/model-weights/gemma-2b",
    "google/gemma-2b-it": "/model-weights/gemma-2b-it",
    "google/gemma-7b": "/model-weights/gemma-7b",
    "google/gemma-7b-it": "/model-weights/gemma-7b-it",
    "zhipu-ai/glm-4v-9b": "/model-weights/glm-4v-9b",
    "gpt2-large": "/model-weights/gpt2-large",
    "gpt2-xl": "/model-weights/gpt2-xl",
    "Salesforce/instructblip-vicuna-7b": "/model-weights/instructblip-vicuna-7b",
    "internlm/internlm2-math-plus-7b": "/model-weights/internlm2-math-plus-7b",
    "Deci/InternVL2_5-26B": "/model-weights/InternVL2_5-26B",
    "Deci/InternVL2_5-38B": "/model-weights/InternVL2_5-38B",
    "Deci/InternVL2_5-8B": "/model-weights/InternVL2_5-8B",
    "TheBloke/Janus-Pro-7B": "/model-weights/Janus-Pro-7B",
    "lfs": "/model-weights/lfs",
    "meta-llama/Llama-2-13b-chat-hf": "/model-weights/Llama-2-13b-chat-hf",
    "meta-llama/Llama-2-13b-hf": "/model-weights/Llama-2-13b-hf",
    "meta-llama/Llama-2-7b-chat-hf": "/model-weights/Llama-2-7b-chat-hf",
    "meta-llama/Llama-2-7b-hf": "/model-weights/Llama-2-7b-hf",
    "meta-llama/Llama-3.1-Nemotron-70B-Instruct-HF": "/model-weights/Llama-3.1-Nemotron-70B-Instruct-HF",
    "meta-llama/Llama-3.2-11B-Vision": "/model-weights/Llama-3.2-11B-Vision",
    "meta-llama/Llama-3.2-11B-Vision-Instruct": "/model-weights/Llama-3.2-11B-Vision-Instruct",
    "meta-llama/Llama-3.2-1B": "/model-weights/Llama-3.2-1B",
    "meta-llama/Llama-3.2-1B-Instruct": "/model-weights/Llama-3.2-1B-Instruct",
    "meta-llama/Llama-3.2-3B": "/model-weights/Llama-3.2-3B",
    "meta-llama/Llama-3.2-3B-Instruct": "/model-weights/Llama-3.2-3B-Instruct",
    "meta-llama/Llama-3.2-90B-Vision": "/model-weights/Llama-3.2-90B-Vision",
    "meta-llama/Llama-3.2-90B-Vision-Instruct": "/model-weights/Llama-3.2-90B-Vision-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct": "/model-weights/Llama-3.3-70B-Instruct",
    "LLaMA-Consortium/Llama3-OpenBioLLM-70B": "/model-weights/Llama3-OpenBioLLM-70B",
    "haotian-liu/llava-1.5-13b-hf": "/model-weights/llava-1.5-13b-hf",
    "haotian-liu/llava-1.5-7b-hf": "/model-weights/llava-1.5-7b-hf",
    "llava-med/llava-med-v1.5-mistral-7b": "/model-weights/llava-med-v1.5-mistral-7b",
    "haotian-liu/llava-v1.6-34b-hf": "/model-weights/llava-v1.6-34b-hf",
    "haotian-liu/llava-v1.6-mistral-7b-hf": "/model-weights/llava-v1.6-mistral-7b-hf",
    "meta-llama/Meta-Llama-3.1-405B-Instruct": "/model-weights/Meta-Llama-3.1-405B-Instruct",
    "meta-llama/Meta-Llama-3.1-70B": "/model-weights/Meta-Llama-3.1-70B",
    "meta-llama/Meta-Llama-3.1-70B-Instruct": "/model-weights/Meta-Llama-3.1-70B-Instruct",
    "meta-llama/Meta-Llama-3.1-8B": "/model-weights/Meta-Llama-3.1-8B",
    "meta-llama/Meta-Llama-3.1-8B-Instruct": "/model-weights/Meta-Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.1-8B-Instruct": "/model-weights/Meta-Llama-3.1-8B-Instruct",
    "meta-llama/Meta-Llama-3-70B": "/model-weights/Meta-Llama-3-70B",
    "meta-llama/Meta-Llama-3-70B-Instruct": "/model-weights/Meta-Llama-3-70B-Instruct",
    "meta-llama/Meta-Llama-3-8B": "/model-weights/Meta-Llama-3-8B",
    "meta-llama/Meta-Llama-3-8B-Instruct": "/model-weights/Meta-Llama-3-8B-Instruct",
    "minicpm/MiniCPM-Llama3-V-2_5": "/model-weights/MiniCPM-Llama3-V-2_5",
    "ministerial/Ministral-8B-Instruct-2410": "/model-weights/Ministral-8B-Instruct-2410",
    "mistralai/Mistral-7B-Instruct-v0.1": "/model-weights/Mistral-7B-Instruct-v0.1",
    "mistralai/Mistral-7B-Instruct-v0.2": "/model-weights/Mistral-7B-Instruct-v0.2",
    "mistralai/Mistral-7B-Instruct-v0.3": "/model-weights/Mistral-7B-Instruct-v0.3",
    "mistralai/Mistral-7B-v0.3": "/model-weights/Mistral-7B-v0.3",
    "mistralai/Mistral-Large-Instruct-2407": "/model-weights/Mistral-Large-Instruct-2407",
    "mistralai/Mistral-Large-Instruct-2411": "/model-weights/Mistral-Large-Instruct-2411",
    "mistralai/Mixtral-8x22B-Instruct-v0.1": "/model-weights/Mixtral-8x22B-Instruct-v0.1",
    "mistralai/Mixtral-8x22B-v0.1": "/model-weights/Mixtral-8x22B-v0.1",
    "mistralai/Mixtral-8x7B-Instruct-v0.1": "/model-weights/Mixtral-8x7B-Instruct-v0.1",
    "Aeala/Molmo-7B-D-0924": "/model-weights/Molmo-7B-D-0924",
    "google/mt5-xl-lm-adapt": "/model-weights/mt5-xl-lm-adapt",
    "allenai/OLMo-1B-hf": "/model-weights/OLMo-1B-hf",
    "allenai/OLMo-7B": "/model-weights/OLMo-7B",
    "allenai/OLMo-7B-hf": "/model-weights/OLMo-7B-hf",
    "allenai/OLMo-7B-SFT": "/model-weights/OLMo-7B-SFT",
    "microsoft/Phi-3.5-vision-instruct": "/model-weights/Phi-3.5-vision-instruct",
    "microsoft/Phi-3-medium-128k-instruct": "/model-weights/Phi-3-medium-128k-instruct",
    "microsoft/Phi-3-vision-128k-instruct": "/model-weights/Phi-3-vision-128k-instruct",
    "AI-Mixers/Pixtral-12B-2409": "/model-weights/Pixtral-12B-2409",
    "AI-Mixers/Pixtral-12B-2409_original": "/model-weights/Pixtral-12B-2409_original",
    "Qwen/Qwen1.5-72B-Chat": "/model-weights/Qwen1.5-72B-Chat",
    "Qwen/Qwen2-1.5B-Instruct": "/model-weights/Qwen2-1.5B-Instruct",
    "Qwen/Qwen2.5-0.5B-Instruct": "/model-weights/Qwen2.5-0.5B-Instruct",
    "Qwen/Qwen2.5-14B-Instruct": "/model-weights/Qwen2.5-14B-Instruct",
    "Qwen/Qwen2.5-1.5B-Instruct": "/model-weights/Qwen2.5-1.5B-Instruct",
    "Qwen/Qwen2.5-32B-Instruct": "/model-weights/Qwen2.5-32B-Instruct",
    "Qwen/Qwen2.5-3B-Instruct": "/model-weights/Qwen2.5-3B-Instruct",
    "Qwen/Qwen2.5-72B-Instruct": "/model-weights/Qwen2.5-72B-Instruct",
    "Qwen/Qwen2.5-7B-Instruct": "/model-weights/Qwen2.5-7B-Instruct",
    "Qwen/Qwen2.5-Coder-7B-Instruct": "/model-weights/Qwen2.5-Coder-7B-Instruct",
    "Qwen/Qwen2.5-Math-1.5B-Instruct": "/model-weights/Qwen2.5-Math-1.5B-Instruct",
    "Qwen/Qwen2.5-Math-72B-Instruct": "/model-weights/Qwen2.5-Math-72B-Instruct",
    "Qwen/Qwen2.5-Math-7B": "/model-weights/Qwen2.5-Math-7B",
    "Qwen/Qwen2.5-Math-7B-Instruct": "/model-weights/Qwen2.5-Math-7B-Instruct",
    "Qwen/Qwen2.5-VL-7B-Instruct": "/model-weights/Qwen2.5-VL-7B-Instruct",
    "Qwen/Qwen2-Math-1.5B-Instruct": "/model-weights/Qwen2-Math-1.5B-Instruct",
    "Qwen/Qwen2-Math-72B": "/model-weights/Qwen2-Math-72B",
    "Qwen/Qwen2-Math-72B-Instruct": "/model-weights/Qwen2-Math-72B-Instruct",
    "Qwen/Qwen2-Math-7B-Instruct": "/model-weights/Qwen2-Math-7B-Instruct",
    "Qwen/Qwen2-VL-7B-Instruct": "/model-weights/Qwen2-VL-7B-Instruct",
    "QwQ/QwQ-32B-Preview": "/model-weights/QwQ-32B-Preview",
    "runwayml/sd-v1-4-full-ema": "/model-weights/sd-v1-4-full-ema",
    "runwayml/stable-diffusion-v1-4": "/model-weights/stable-diffusion-v1-4",
    "google/t5-large-lm-adapt": "/model-weights/t5-large-lm-adapt",
    "google/t5-xl-lm-adapt": "/model-weights/t5-xl-lm-adapt",
}
